services:
  - type: web
    name: forgetrack-api
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py loaddata initial_exercises
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0