# Generated by Django 6.0 on 2026-03-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='is_compound',
            field=models.BooleanField(default=False, help_text='Is this a base/compound move? (Ex: Bench Press, Squat)'),
        ),
    ]
