# Generated by Django 6.0 on 2026-03-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_exercise_is_compound'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineitem',
            name='day_name',
            field=models.CharField(default='Monday', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='is_compound',
            field=models.BooleanField(default=False, help_text='Is this a base/compound move?'),
        ),
    ]
