# Generated by Django 6.0 on 2026-03-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_routineitem_day_name_alter_exercise_is_compound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
